name: CI

on:
    schedule:
        - cron: '00 1 * * 2'
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    run:
        runs-on: ubuntu-latest
        strategy:
            matrix:
              include:
                - php-version: '8.1'
                  main: true
                - php-version: '8.2'
                - php-version: '8.3'
                - php-version: '8.4'
                  nightly: true
        name: PHP ${{ matrix.php-version }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  coverage: pcov
                  php-version: ${{ matrix.php-version }}

            - name: Get Composer Cache Directory
              id: composer-cache
              run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            - uses: actions/cache@v4
              with:
                path: ${{ steps.composer-cache.outputs.dir }}
                key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                restore-keys: ${{ runner.os }}-composer-

            - name: Install dependencies
              run: composer install --prefer-dist --dev

            - name: Run tests
              run: ./vendor/bin/phpunit
              continue-on-error: ${{ matrix.nightly }}

            - name: Run code style check
              if: ${{ matrix.main }}
              run: ./vendor/bin/ecs

            - name: Run rector
              if: ${{ matrix.main }}
              run: ./vendor/bin/rector --dry-run

            - name: Upload coverage reports to Codecov
              if: ${{ matrix.main }}
              uses: codecov/codecov-action@v4
              env:
                CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

