name: CI

on:
    schedule:
        - cron: '00 1 * * 2'
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
env:
  PHP_MIN: 8.1
jobs:
    run:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-versions: [ env.PHP_MIN, '8.2', '8.3']
        name: PHP ${{ matrix.php-versions }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  coverage: pcov
                  php-version: ${{ matrix.php-versions }}

            - name: Get Composer Cache Directory
              id: composer-cache
              run: |
                  echo "::set-output name=dir::$(composer config cache-files-dir)"
            - uses: actions/cache@v2
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-

            - name: Install dependencies
              run: composer install --prefer-dist --dev

            - name: Run tests
              run: ./vendor/bin/phpunit

            - name: Run code style check
              if: matrix.php-version == env.PHP_MIN
              run: ./vendor/bin/ecs

            - name: Upload coverage reports to Codecov
              if: matrix.php-version == env.PHP_MIN
              uses: codecov/codecov-action@v3
              env:
                CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

